openapi: 3.0.0
info:
  title: API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/products/{id}':
    get:
      summary: '/products/{id}'
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
      operationId: get-products
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
  /store:
    post:
      summary: /store
      operationId: post-store
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QR-Payload'
    parameters: []
components:
  schemas:
    Product:
      title: 'Model: Product'
      type: object
      properties:
        id:
          type: string
        information:
          $ref: '#/components/schemas/QR-Payload'
        mdd:
          type: string
        storagePlace:
          type: object
    QR-Payload:
      title: 'Model: QR-Payload'
      type: object
      properties:
        fruitType:
          type: string
        amount:
          type: integer
        storageDate:
          type: string
        comments:
          type: string
      description: ''
  securitySchemes: {}
